USE compta;


SELECT *  FROM  ARTICLE;



SELECT  DESIGNATION,PRIX FROM ARTICLE WHERE PRIX  > 2;


SELECT PRIX  FROM ARTICLE WHERE PRIX = 2 AND 6.25;


SELECT PRIX FROM ARTICLE WHERE PRIX  BETWEEN 2 AND 6.25;

SELECT PRIX FROM ARTICLE WHERE  PRIX NOT BETWEEN 2 AND  6.25 ORDER PRIX DESC;

SELECT * FORM FOURNISSEUR WHERE  NOM  = 'Française d''Imports' AND 'Dubois & Fils';

SELECT * IN FOURNISSEUR WHERE NOM   = 'Française d Imports' AND 'Dubois & Fils';

SELECT *  IN FOURNISSEUR WHERE NOM  NOT = 'Française d''Imports' AND 'Dubois & Fils';

SELECT * FROM BON WHERE DATE = '01/02/2019' AND '30/04/2019';